@Library('singularity_template@main') _

def defaults = [
    sshUser: 'wlp9800',
    image: 'devenv-cpu',
    scratchDir: '/scratch/wlp9800',
    logDir: '/vast/wlp9800/logs',
    dockerUrl: 'docker://thewillyp/devenv-cpu',
    forceRebuild: false,
    overlaySrc: '/scratch/work/public/overlay-fs-ext3/overlay-25GB-500K.ext3.gz',
    buildTime: '00:30:00',
    buildCPUs: '8',
    buildMem: '10G',
    runTime: '06:00:00',
    runCPUs: '4',
    runMem: '14G',
    entrypointUrl: 'https://raw.githubusercontent.com/thewillyP/devenv/master/entrypoint.sh',
]

singularityPipeline(defaults)
