@Library('singularity_template@main') _

def defaults = [
    sshUser: 'wlp9800',
    image: 'devenv-cpu',
    scratchDir: '/scratch/wlp9800',
    logDir: '/vast/wlp9800/logs',
    dockerUrl: 'docker://thewillyp/devenv-cpu',
    forceRebuild: false,
    overlaySrc: '/scratch/work/public/overlay-fs-ext3/overlay-25GB-500K.ext3.gz',
    buildTime: '00:30:00',
    buildCPUs: '8',
    buildMem: '10G',
    runTime: '06:00:00',
    runCPUs: '4',
    runMem: '14G',
    entrypointUrl: 'https://raw.githubusercontent.com/thewillyP/devenv/master/entrypoint.sh',
    binds: "/home/wlp9800/dev,/scratch/wlp9800/wandb:/wandb_data,/scratch/wlp9800/space:/scratch",
    useGpu: false 
]

def runJobId = singularityPipeline(defaults)

pipeline {
    agent any

    environment {
        SSH_USER = "${defaults.sshUser}"
        IMAGE    = "${defaults.image}"
        LOG_DIR  = "${defaults.logDir}"
        SCRIPT_BASE_URL = 'https://raw.githubusercontent.com/thewillyP/jenkins/main'
    }

    stages {
        stage('Submit DNS Update Job') {
            steps {
                script {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${SSH_USER}@${env.EXEC_HOST} \\
                      'curl -fsSL ${SCRIPT_BASE_URL}/submit_dns_job.sh | \\
                      bash -s ${runJobId} ${IMAGE} ${LOG_DIR} dns-update-${IMAGE} 1G 00:05:00 1 ${SSH_USER}'
                    """
                }
            }
        }
    }
}
