name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'    
      - .dockerignore     
      - '.github/workflows/**'    
      - 'requirements-cpu.txt'
      - 'requirements-gpu.txt'      
  pull_request:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'         
      - '.github/workflows/**'  

jobs:
  docker:
    strategy:
      matrix:
        variant: [cpu, gpu] 
    uses: thewillyP/ReusableWorkflow/.github/workflows/main.yml@main
    with:
      image_name: devenv 
      tags: |
        1.0.${{ github.run_number }}-${{ matrix.variant }}
        type=ref,event=tag
        type=raw,value=${{ matrix.variant }}
      build_args: VARIANT=${{ matrix.variant }}  # Pass the variant as a build argument
      cache-from: type=gha,scope=${{ matrix.variant }}
      cache-to: type=gha,mode=max,scope=${{ matrix.variant }}
    secrets: inherit
