name: ci

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'deploy/**'
      - 'entrypoint.sh'
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        variant: [cpu, gpu] 
    uses: thewillyP/ReusableWorkflow/.github/workflows/main.yml@main
    with:
      image_name: devenv 
      tags: |
        1.0.${{ github.run_number }}-${{ matrix.variant }}
        type=ref,event=tag
        type=raw,value=${{ matrix.variant }}
      build_args: VARIANT=${{ matrix.variant }}  # Pass the variant as a build argument
    secrets: inherit
